SCR_MapConfig : "{1B8AC767E06A0ACD}Configs/Map/MapFullscreen.conf" {
 m_aUIComponents {
    SCR_MapCampaignUI "{5A0F0000000000D1}" {
     m_bDisableComponent 1
    }
    SCR_MapLightUI "{5A0F0000000000D2}" {
     m_bDisableComponent 1
    }
    SCR_MapRulerUI "{5A0F0000000000D3}" {
     m_bDisableComponent 1
    }
    SCR_MapTaskListUI "{5A0F0000000000D4}" {
     m_bDisableComponent 1
    }
    SCR_MapUIElementContainer "{5A0F0000000000D5}" {
     m_bDisableComponent 1
    }
   }
}
