MenuManager : "{C747AFB6B750CE9A}Configs/System/chimeraMenus.conf" {
 MenuPresets {
   MenuPreset LobbyMenu {
    Layout "{4F92A527A40CA903}UI/layouts/Melis_LobbyScreen_v2.layout"
    ActionContext "MapContext"
    Class "LobbyMenu"
   }
 }
}