ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
 Contexts {
  ActionContext LobbyContext {
   Priority 50
   ActionRefs {
    "ChatToggle"
    "VONDirect"
    "MenuBack"
    "VONChannel"
    "EditorToggle"
   }
  }
 }
}