ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
  Actions {
   Action LobbyVoN {
    InputSource InputSourceSum "AA00010800000001" {
     Sources {
      InputSourceValue "AA00010800000002" {
       Input "keyboard:KC_T"
       Filter InputFilterHold "AA00010800000003" {
       }
      }
     }
    }
   }
   Action LobbyGameForceStart {
    InputSource InputSourceValue "AA00010800000004" {
     Input "keyboard:KC_RETURN"
     Filter InputFilterPressed "AA00010800000005" {
     }
    }
   }
   Action LobbyMapOpen {
    InputSource InputSourceValue "AA00010900000021" {
     Input "keyboard:KC_M"
     Filter InputFilterPressed "AA00010900000022" {
     }
    }
   }
  }
   Contexts {
ActionContext MapContext {
ActionRefs +{
       "ChatToggle"
       "LobbyVoN"
       "MenuBack"
       "EditorToggle"
       "LobbyGameForceStart"
       "LobbyMapOpen"
      }
    }
ActionContext MenuContext {
ActionRefs +{
       "LobbyMapOpen"
      }
    }
  }
}